; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "myRIO_Installer"
#define MyAppVersion "2.02"
#define MyAppPublisher "Petrus Prins"
#define MyAppURL "https://github.com/petrus-prins/myRIO_Beyond_LV2021_Installer"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{077EED15-B543-4557-8DFC-8DE7FC35B8EC}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
;DefaultDirName={autopf}
DefaultGroupName={#MyAppName}

; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=E:\
OutputBaseFilename={#MyAppName}_v{#MyAppVersion}
SolidCompression=yes
WizardStyle=modern dynamic
LicenseFile=E:\2__Tools\_inno_scripts\License_File.txt
InfoBeforeFile=E:\2__Tools\_inno_scripts\Before_Install.txt
InfoAfterFile=E:\2__Tools\_inno_scripts\After_Install.txt
UninstallFilesDir = {app}\{#MyAppName}

DefaultDirName=C:\Program Files (x86)\National Instruments\LabVIEW 2000
DisableDirPage=no
AppendDefaultDirName=no


[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
;Source: "E:\1__Originals\2__Extracted\LabVIEW 2021\Petrus\*"; DestDir: "{app}\_Petrus"; Flags: ignoreversion recursesubdirs createallsubdirs
;Source: "E:\1__Originals\2__Extracted\LabVIEW 2021\resource\*"; DestDir: "{app}\resource"; Flags: ignoreversion recursesubdirs createallsubdirs
;Source: "E:\1__Originals\2__Extracted\LabVIEW 2021\Targets\*"; DestDir: "{app}\Targets"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: "E:\1__Originals\2__Extracted\LabVIEW 2021\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "E:\1__Originals\2__Extracted\Shared\*"; DestDir: "{app}\..\Shared"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "E:\1__Originals\2__Extracted\_Legal Information\*"; DestDir: "{app}\..\_Legal Information"; Flags: ignoreversion recursesubdirs createallsubdirs



; NOTE: Don't use "Flags: ignoreversion" on any shared system files

